// AUTO-GENERATED by scripts/gen-subpage-i18n.mjs — do not edit by hand.
import type { Locale } from "@/lib/i18n/dictionary";
import { SUPPORTED_LOCALES } from "@/lib/i18n/dictionary";
import type { SubpageKey } from "./en";
import en from "./en";
import zh from "./zh";
import zhHant from "./zh-Hant";
import es from "./es";
import fr from "./fr";
import de from "./de";
import hi from "./hi";
import tr from "./tr";
import ar from "./ar";
import id from "./id";
import fil from "./fil";
import ru from "./ru";
import pl from "./pl";
import nl from "./nl";
import vi from "./vi";
import ja from "./ja";
import pt from "./pt";
import it from "./it";
import th from "./th";
import ko from "./ko";
import sv from "./sv";
import he from "./he";

export type { SubpageKey } from "./en";
export { SUPPORTED_LOCALES }
export type SubpageLocale = Locale;

export const subTranslations: Record<Locale, Record<SubpageKey, string>> = {
  en,
  "zh": zh,
  "zh-Hant": zhHant,
  "es": es,
  "fr": fr,
  "de": de,
  "hi": hi,
  "tr": tr,
  "ar": ar,
  "id": id,
  "fil": fil,
  "ru": ru,
  "pl": pl,
  "nl": nl,
  "vi": vi,
  "ja": ja,
  "pt": pt,
  "it": it,
  "th": th,
  "ko": ko,
  "sv": sv,
  "he": he,
};

export function getSubT(locale: Locale): (key: SubpageKey) => string {
  const dict = subTranslations[locale] ?? en;
  return (key: SubpageKey) => dict[key] ?? en[key] ?? (key as string);
}
