import type { MetadataRoute } from "next";

const SITE_URL = "https://ytplaylistlength.pro";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/", "/_next/", "/admin/"],
    },
    // Host directive (canonical domain). Note: Next's MetadataRoute.Robots
    // supports `host`; it renders as the Host: line in robots.txt.
    host: SITE_URL,
    // Sitemap references. The main sitemap is generated by app/sitemap.ts;
    // the image sitemap remains a static file at /sitemap-images.xml.
    sitemap: [`${SITE_URL}/sitemap.xml`, `${SITE_URL}/sitemap-images.xml`],
    // NOTE: The previous static robots.txt also declared `Crawl-delay: 1`.
    // That directive is not part of Next's MetadataRoute.Robots type and most
    // modern crawlers ignore it, so it is intentionally omitted here.
  };
}
